# Note that `target` is used as the output directory for Rust so care should be
# taken that collisions don't occur between Rust output and local output.
tgt_dir:=target

.PHONY: check
check: \
	check_style \
	check_lint

.PHONY: check_style
check_style: $(tgt_dir)/deps/dpnd/scripts/check_line_length.py
	comment_style comment_style.yaml
	python3 $(tgt_dir)/deps/dpnd/scripts/check_line_length.py \
		'src/**/*.rs' \
		79

# We allow `clippy::just-underscores-and-digits` because the code generated by
# LALRPOP creates variables that are denied by this lint.
.PHONY: check_lint
check_lint:
	cargo clippy \
		--all-targets \
		--all-features \
		-- \
		--deny warnings \
		--deny clippy::pedantic \
		--deny clippy::cargo \
		--allow clippy::module-name-repetitions
# NOCOMMIT Remove module-name-repititions.

$(tgt_dir)/deps/dpnd/scripts/check_line_length.py:
	dpnd install
